# Generated by Django 4.1.2 on 2023-04-30 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('side_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_a', to=settings.AUTH_USER_MODEL)),
                ('side_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
