# Generated by Django 4.1.2 on 2023-04-30 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogue',
            options={'ordering': ['-last_activity']},
        ),
        migrations.CreateModel(
            name='TestMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.dialogue')),
            ],
        ),
    ]
