# Generated by Django 4.1.2 on 2023-04-30 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
        migrations.DeleteModel(
            name='TestMsg',
        ),
    ]
