# Generated by Django 4.1.2 on 2023-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='msg_count',
            field=models.IntegerField(default=0),
        ),
    ]
