# Generated by Django 4.1.2 on 2023-05-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_dialogue_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogue',
            name='is_read',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='is_read_by_side_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='is_read_by_side_b',
            field=models.BooleanField(default=False),
        ),
    ]
