# Generated by Django 4.1.2 on 2023-04-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-id']},
        ),
    ]
