# Generated by Django 4.1.2 on 2023-04-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_date_test_alter_test_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='date_test',
            name='smth',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
