# Generated by Django 4.1.2 on 2023-04-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_delete_date_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='test',
            name='sub_text',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
