# Generated by Django 4.1.2 on 2023-04-24 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_alter_tweet_options_test_sub_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
