# Generated by Django 4.1.2 on 2023-04-29 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0009_rates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rates',
            new_name='Rate',
        ),
    ]
