# Generated by Django 4.1.2 on 2023-04-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_alter_comment_text_alter_tweet_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
